### ISSUE TITLE
配置疑惑

### ISSUE THREAD

**Issue by coki230** [bbossgroups/elasticsearch-example#1]
你好，最近有个问题一直困惑着我，麻烦你帮忙提醒一下我那边理解的有问题。
elasticsearch.rest.hostNames=10.180.211.27:9280,10.180.211.27:9281,10.180.211.27:9282
bboss后台用的是http的client和ES交互，配置多个IP有什么用，因为ES数据处理都是在访问的节点处理分发后在此节点整合返回的，所有是否只有一个IP就可以了，其他没有实际意义？

**Comment by yin-bp** [comment]
配置多个ip的作用：
1.负载均衡：bboss可以把对es的操作均衡的分发到各个es集群节点，这样达到负载均衡的目的
2.容灾：如果某个节点不可访问，请求就会发到其他节点上面去，当节点恢复后又能继续分发请求给它

**Comment by coki230** [comment]
1.负载均衡：
实际请求的节点只是一个协调节点，它会把请求再去重新分配的，ES本身就是负载均衡的，而且写操作只能在主节点上做，这时候唯一的影响就是单节点流量瓶颈问题，但是这个一般不会高并发。
多个节点接收请求有几率有写冲突的问题（两个节点同时处理同一个ID的更新操作），ES虽然用乐观锁解决了，但是返回可能体现不出来。
2.容灾：
这个功能没想到，多谢提醒。
