### ISSUE TITLE
个人反馈：API设计太复杂

### ISSUE THREAD

**Issue by kevinhuangwl** [bbossgroups/elasticsearch-example#3]
看完几个DEMO后，个人感觉是，与官方的HighLevelRestClient的JAVA API相比，感觉BBOSS的设计没有简化操作。有点望而却步的感觉

**Comment by yin-bp** [comment]
@kevinhuangwl 感谢你的关注bboss，说得有点笼统，能否具体化一下，比如举个例子对比一下。
bboss最大的一点改进就是dsl管理采用类似mybatis管理sql的方式管理elasticsearch 检索查询dsl语句

更多信息，请关注bboss文档；
https://esdoc.bbossgroups.com/

**Comment by kevinhuangwl** [comment]
如果bboss的最大亮点在于集中式管理dsl，那个人肤浅地认为，即使没有bboss我也可以实现这一点：无非就是读JSON文本，然后映射相应的值，最后发HTTP请求。
 &nbsp;
 mybatis的亮点在于不光光集中管理了SQL语句，还在代码层面极大地简化，从而提高开发效率。这一点我暂时在bboss的demo中体会不到。

  

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"大河"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年9月30日(星期一) 下午3:15
 收件人:&nbsp;"bbossgroups/elasticsearch-example"<elasticsearch-example@noreply.github.com&gt;;
 抄送:&nbsp;"◆亮◆/:)"<12959229@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [bbossgroups/elasticsearch-example] 个人反馈：API设计太复杂 (#3)

 

 
@kevinhuangwl 感谢你的关注bboss，说得有点笼统，能否具体化一下，比如举个例子对比一下。
bboss最大的一点改进就是dsl管理采用类似mybatis管理sql的方式管理elasticsearch 检索查询dsl语句
 
更多信息，请关注bboss文档；
https://esdoc.bbossgroups.com/

**Comment by yin-bp** [comment]
管理dsl只是亮点之一，bboss的开发代码也很简洁，提供的ormapping机制也还行，对开发效率也能有所提升
这点bboss的开发使用者还是比较认可的，下面是bboss增删改查的文档

https://esdoc.bbossgroups.com/#/document-crud
下面是quickstart文档
https://esdoc.bbossgroups.com/#/quickstart

**Comment by yin-bp** [comment]
bboss Support elasticsearch 1.x,2.x,5.x,6.x,7.x,+，support spring boot 1.x,2.x
