### ISSUE TITLE
我想自定义es _id

### ISSUE THREAD

**Issue by ironbang** [bbossgroups/elasticsearch-example#7]
https://github.com/bbossgroups/elasticsearch-example/blob/ff0991157a025e1c7f4642923542aff2b367296f/src/test/java/org/bboss/elasticsearchtest/bulkprocessor/TestBulkProcessor.java#L145

我的data是Map<String,String>，如果我将id put到data中，然后再使用ClientOption.setIdField("id")，结果我在我的索引的source中看到有id这个字段（自动生成的）。请问怎么才能达到文档id是我指定的，但是source中不包含这个字段呢？

**Comment by yin-bp** [comment]
Hi,@ironbang

如果是map的话，你可以不要ClientOption.setIdField("id")，而是直接设置通过ClientOption设置id值：ClientOption.setId("xxxxx")

如果是java bean的情况，则可以在对象属性上添加注解ESId忽略掉要保存id属性（但是读取的时候设置文档id）：
@ESId(persistent = false,readSet=true)
private String id;

bboss客户端注解使用文档
https://esdoc.bbossgroups.com/#/client-annotation

**Comment by ironbang** [comment]
ClientOptions clientOptions = new ClientOptions(); 
clientOptions.setId("123456");    
Map<String,Object> data = new HashMap<String,Object>();
data.put("message","duoduo1");
bulkProcessor.insertData("twitter","tweet",data,clientOptions);

es结果：
      {
        "_index": "twitter",
        "_type": "tweet",
        "_id": "AXYsRgXuibt7rG_Tjyk1",
        "_score": 1,
        "_source": { - 
          "message": "duoduo1"
        }
      }

我看了源码，getId没有被调用。

**Comment by yin-bp** [comment]
ok，我修复一下

**Comment by ironbang** [comment]
谢啦
